/**
 * Created by mwindson on 2016/12/5.
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
// todo
public class Problem389 {
    public static void main(String[] args) {
        String s = "";
        String t = "e";
        System.out.print(findTheDifference(s, t));
    }

    public static char findTheDifference(String s, String t) {
        return ' ';
    }
}
