import java.util.Scanner;

/**
 * Created by mwindson on 2017/4/30.
 */
public class Tmp {
    public static void main(String[] args) {
//        String[][] map = {
//                {"I have always, and still do, enjoy teaching Catherine. Having said this, I would still like to see Catherine participate more in class by raising her hand and offering an opinion in class discussion. When I call on her to answer, she always can, I just wish she wouldn't wait for me to specifically call on her.\n" +
//                        "In her listening, Catherine is able to distinguish movie genres and descriptions of these genres. Catherine can also distinguish activities that people have completed when giving a series of options. In class, Catherine can always answer questions she asked, showing she has a sound comprehension.\n" +
//                        "In her speaking, Catherine can tell me rules that should be followed, using 'must, need to and should'. Catherine can also give advice for illnesses that people may be suffering from.\n" +
//                        "Great work!", "I often see Catherine reading before class starts, given that she clearly enjoys reading, I would suggest that she begin to read some English books. Books such as Robinson Crusoe would be a really good place for her to start. This would help her reading comprehension. I also recommend she continue with her online homework and pay attention to reader activities as she is still struggling to read longer passages. "},
//                {"Coco is a really great student who makes a lot of effort in class. She is always one of the first to raise her hand to volunteer answers or read aloud, qualities I really admire in her.\n" +
//                        "In her speaking, Coco is able to offer advice and suggestions to someone's illness. For example, Coco is able to ask someone 'how did you hurt yourself?' and then 'you have a sprained wrist, you should wear a bandage. You need to rest'. Coco can also offer cooking advice, using cooking verbs such as 'grill' and 'fry'.\n" +
//                        "In her listening, Coco is able to listen to a description of a movie and tell you about the movie genre and how the movie is described. \n" +
//                        "Great work Coco!", "Coco is really great all round in her English abilities, showing she has some really great study habits that I would like to see her continue to deploy. A minor area of improvement would be in her spelling of key lexis. I suggest you try some dictation exercises with Coco and use game 1 of the HF online to continue spelling practice. "},
//                {"Eason has a really good all round ability in English, showcased not only through his strong assessment scores, but his attitude in class is very good. He always volunteers to read aloud in class and helps to answer questions. Recently, I have asked him to help teach his peers that may be struggling.\n" +
//                        "In his speaking, Eason can successfully talk about different genres of movies, including what genres he likes and dislikes, and why. For example 'i don't like romantic movies they are too boring. I like action movies, they are so exciting'. Eason can also offer advice to illness, using imperatives such as 'need to' and 'should'. Eason can say 'you have a high fever. You need to drink some hot water. You should stay in bed'.\n" +
//                        "Good work Eason. ", "Eason has not yet completed any of the online homework. Although it is clear that Eason has some really good study habits, I think he would still benefit from overall review of what we have learnt to date, especially as he missed some lessons during spring festival. I think it is important that he reviews the work that he missed during this time. "},
//                {"Elaine has recently been very distracted in class and I often have to call on her very often in order to ensure she is paying attention to the class content. I really need Elaine to pay attention in class especially as she is really struggling in her reading.\n" +
//                        "In her listening, Elaine can listen to a person giving a list of instructions and match these instructions to a corresponding image that represents the rule. For example, when a person describes that they are ill and as such they shouldn't leave home or do sports, Elaine could successfully match this with an image of a person climbing a tree. Elaine can also listen to a description of a movie and name the movie genre that the movie belongs to. ", "Elaine's biggest weakness is her reading. She is struggling to read aloud, she cannot find specific information from within a text and cannot answer concept questions about what she has read. She really needs to work on this. I suggest that she re-reads all of the readers we have so far read in class- this means reading them aloud in order to decode any unfamiliar words. She should then find specific information from within the reader, such as target lexis from each unit so she can practice scanning a text. She should then complete her online reading homework to answer concept checking questions on what she has read. "},
//                {"Jerry is always very talkative in class, which generally is a good thing as he likes to be part of the classroom dynamic. However, when I then call on Jerry to answer a specific question, he will often refuse to listen to the question and refuse to answer which I find quite frustrating. I would like it if Jerry could better concentrate his efforts and answer questions with a specific context relation.\n" +
//                        "In his listening, Jerry is able to listen to a description of a movie and tell you what the genre of the movie is and can also then sequence the order of the movie if given a set of images. Jerry can also listen to a recipe and tell you what cooking verbs were used and what ingredients are used.\n" +
//                        "Good job.", "Jerry needs to work on his reading, specifically extracting information from a large body of text. To help with this, I suggest that Jerry re-reads the graded readers and from each reader underlines key lexis- such as the target lexis from each unit. This will help him extract key information from a large body of text. Jerry should also continue to make use of his online homework. "},
//                {"In class, Kiki always has a smile on her face and loves to get involved in classroom discussions an the classroom dynamic which I always appreciate.\n" +
//                        "In her writing, Kiki can offer advice to medical issues, using imperatives such as need to and should. Kiki can write 'you have a fever. You should drink hot water. You need to stay in bed'. Kiki can also begin to describe movies, including what genre the movie is, and what happens in the movie using sequencing vocabulary, such as first/then/next. However, after writing an extended piece of writing, I would like Kiki to re-read her writing in order to proof read for mistakes that I would no longer be expecting her to make, such as issues in her tensing. ","Kiki's biggest area of concern is her reading. I have found that because she struggles in this area, she often doesn't concentrate in class when we start a reading activity. I really need her to concentrate in this area in order to better understand it. Kiki should make good use of her online homework to help concept check reading knowledge. I would also like Kiki to go back through her grey exercise book and re-read the questions that are asked in each reading section to help as a basis for concept checking. "},
//                {"I have always enjoyed teaching Lucas, but since reaching HFH I have noticed that he has become a little withdrawn and I suspect that it is because he is struggling with the course content, which is reflected in his assessment records which are lower than I would hope for Lucas. As such, I will be monitoring his progress and assessing what is best for Lucas going forward.\n" +
//                        "Lucas' listening s particularly strong. Lucas is able to listen to descriptions of movies, including a plot outline of what happens in the movie and link this to a particular movie genre and can then describe the movie using adjectives such as 'interesting or too boring' to describe the movie. Lucas can also distinguish rules using should and shouldn't.","I really would like Lucas to focus on his writing. Generally his grammar in his writing is good, but he often cannot spell the key lexis or even remember the key lexis. For example, during the assessment in unit 3, based on sicknesses and treatments, Lucas could not remember fever, or food poisoning, or sprained wrist. He also could not remember possible treatments for them, such as taking medicine, having an xray or wearing a bandage. This means there is nothing for me to mark in terms of his writing. It is by far his biggest weakness at this point. He really needs to work on remembering key lexis for each unit, as this is a recurring theme in each assessment. I suggest that Lucas write at least three sentences at the end of each lesson to recap what we have learnt that week. Lucas should make use of his online homework to check any lexis or structures he is unfamiliar with. "},
//                {"Michael's behaviour has improved greatly recently. Generally, I only have to ask Michael once to stop his inappropriate behaviour and he will, which shows a lot of growth and maturity in Michael which I am really pleased to see. \n" +
//                        "In Michael's writing, he how shown that he can successfully sequence activities, using sequencing vocabulary such as first, then, next and finally. Michael can also write about his favourite movie, telling you what happened in the movie, the order that it happened in, and how he felt about the movie, such as 'it was so exciting' or 'it was too boring'. \n" +
//                        "Micheal can also write about advice should you have an illness or ailment. He can so this using imperatives such as 'need to' and 'must'.\n" +
//                        "Good work.","Michael does not always complete his homework on time and must endeavor to complete this on time. \n" +
//                        "Michael has struggled a lot with reading so far, which I am surprised by. In class he has not shown that he struggles with reading and comprehension, and as such, I suspect that in his tests he is rushing through in order to finish quickly and so I would like Michael to take his time during assessments. \n" +
//                        "I also suggest that he play game 2 on the HF online to further practice his reading. "},
//                {"Strawberry is still a really positive influence in this class, always without fail raising her hand to answer questions or volunteering to read aloud to the class.\n" +
//                        "What I also particularly like about Strawberry is that she has created a superhero based on me! Whilst these is extremely complimentary , it is also a good reflection of her willingness to learn and use her English. This superhero has a whole backstory, that Strawberry has written in near perfect English, showing how the English we are learning in class can be put to really good, authentic use. \n" +
//                        "Strawberry's biggest strength is her speaking, once she starts it can be tricky to get her to stop, not that I always wish to! She can describe to you a recipe that she has read about, including what ingredients need to go into a dish and how the dish should be cooked. She can also give you rules that you should use in a kitchen or if you are ill, using must, should and need to.\n" +
//                        "Great work!","Strawberry has excellent study habits so I would just like to see her continue these study habits, including made sufficient use of the online homework and the games that accompany the online homework. "},
//                {"Yoki is generally very quiet in class, but will raise her hand to answer questions which I appreciate.\n" +
//                        "In her listening, Yoki is able to listen to instructions and match them to the corresponding images. For example, Yoki can match 'you shouldn't' to an image of 'climb a tree' when discussing advice for someone who is ill. Yoki can also sequence a movie using sequencing vocabulary such as 'first/then/next'. Yoki can also make an attempt at this in her writing, although I would still like to see her take care over her tenses in her writing.\n" +
//                        "Good job Yoki.","I find that Yoki struggles the most in her reading. When reading aloud, she struggles with sounding out unfamiliar language, and often has to rely on others to fill in gaps in her knowledge, rather than attempting the word herself. I would like Yoki to practice reading aloud at home in order to get used to sounding out familiar words. She should start with the graphic readers from the book as she will be familiar with these from class. After she has finished reading the story, I would like Yoki to then summaraise what she has read, which will check her reading comprehension. Yoki should follow this up by completing her online reading homework to further solidify her reading knowledge. "},
//                {"Yuki is a really great student that I enjoy teaching every week. She is really enthusiastic in class and always so willing to help any student who may be struggling, she is such a positive influence on this class. \n" +
//                        "In her speaking, Yuki is able to sequence activities, using sequencing vocabulary such as 'first/then/next/after/finally'. Yuki can sequence events, including the order of her favourite movies and recipes. Yuki can tell you clearly about what her favourite movie, what genre the movie is and can tell you why she likes, using intensifiers. For example, Yuki can say that she likes a movie because it is 'so funny' or doesn't like a movie because it's 'too boring'.\n" +
//                        "Excellent work!","Yuki is clearly making good progress in her online homework, but I would like to see her make more use of the online homework games. Game 2 could be good for her reading, as she has to read a sentence in order to put a word into the sentence. Yuki could also begin to read some English books, such as Robinson Crusoe which is level appropriate, to expand her reading knowledge. "},
//                {"Yuki is clearly making good progress in her online homework, but I would like to see her make more use of the online homework games. Game 2 could be good for her reading, as she has to read a sentence in order to put a word into the sentence. Yuki could also begin to read some English books, such as Robinson Crusoe which is level appropriate, to expand her reading knowledge. ","I just want Deborah to keep up with her positive learning attitude, meaning completing all her homework on time and completing online homework. Deborah could also begin to read some English books, such as the Harry Potter series as I know she enjoys watching the movies which would give her a really good context for reading the books. "}
//        };
        String prefix = "PTC done by Candice to Mom:目前我们进度已经学到第五单元了，老师的评价是：";
        System.out.println("请输入老师评价：");
        Scanner in = new Scanner(System.in);
        String part1 = "";
        while (in.hasNext()) {
            part1 = part1 + in.next();
        }
        System.out.println("请输入老师建议");
        String part2 = "";
        while (in.hasNext()) {
            part2 = part2 + in.next();
        }
        String out = prefix + part1 + "老师的建议：" + part2;
        System.out.println(out);
    }

//    public static void generate(String[][] map) {
//        String prefix = "PTC done by Candice to Mom:目前我们进度已经学到第五单元了，老师的评价是：";
//        for (int i = 0; i < map.length; i++) {
//            String out = prefix + map[i][0] + "老师的建议：" + map[i][1];
//            System.out.println(out);
//            System.out.println("  ");
//        }
//}
}
